; Kape - Spicetify theme
; https://github.com/gabiuz/kape

[Base]
text               = d4be98
subtext            = bdae8b
main               = 181616
sidebar            = 1e1b1b
player             = 181616
card               = 1e1b1b
shadow             = 1e1b1b
selected-row       = 2e2a2a
button             = e7bb5c
button-active      = f0cc7a
button-disabled    = 928374
tab-active         = d4be98
notification       = 7b8fd4
notification-error = b53535
misc               = 928374

[Accent]
accent             = e7bb5c
